"""empty message

Revision ID: a07e67c00e84
Revises: 
Create Date: 2022-06-20 03:05:53.187085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07e67c00e84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('token', sa.LargeBinary(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_provider'), 'refresh_token', ['provider'], unique=False)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_provider'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
