name: Build dev container image tagged with latest version and short commit hash

on:
  push:
    branches:
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  IMAGE_NAME: ghcr.io/ternaustralia/tokenstore

jobs:
  test:
    uses: ternaustralia/tokenstore/.github/workflows/test.yml@main

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build project
        run: python setup.py bdist_wheel

      - name: Get git-semver tool
        uses: supplypike/setup-bin@v3
        with:
          uri: https://github.com/mdomke/git-semver/releases/download/v6.3.1/git-semver_6.3.1_Linux_x86_64.tar.gz
          name: git-semver
          version: "6.3.1"

      - name: Generate version tag
        id: semver_tag
        run: |
          echo "tag=$(git-semver)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.semver_tag.outputs.tag }}
